/**
 * Optimization report generator.
 * Pure functions that produce Markdown reports from job history and pipeline state.
 * No external dependencies — output is a string suitable for Blob download or print.
 */

import type { JobHistoryRecord } from "@/lib/jobHistoryStore";

export interface ReportOptions {
  title?: string;
  includeRecipeJson?: boolean;
  includeLogSummary?: boolean;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const secs = Math.floor(ms / 1000);
  if (secs < 60) return `${secs}s`;
  const mins = Math.floor(secs / 60);
  const remSecs = secs % 60;
  return `${mins}m ${remSecs}s`;
}

function statusEmoji(status: string): string {
  switch (status) {
    case "completed":
      return "✅";
    case "failed":
      return "❌";
    case "cancelled":
      return "⚠️";
    default:
      return "❓";
  }
}

/**
 * Generate a Markdown optimization report from one or more job history records.
 */
export function generateMarkdownReport(records: JobHistoryRecord[], options: ReportOptions = {}): string {
  const {
    title = "Olive Studio Optimization Report",
    includeRecipeJson = false,
    includeLogSummary = true,
  } = options;
  const now = new Date().toISOString().slice(0, 19).replace("T", " ");
  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`**Generated:** ${now} UTC`);
  lines.push(`**Jobs:** ${records.length}`);
  lines.push("");

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| # | Model | Provider | Status | Duration | Passes | VRAM (GB) |");
  lines.push("|---|-------|----------|--------|----------|--------|-----------|");

  records.forEach((rec, i) => {
    const vram = rec.vramEstimateGb != null ? rec.vramEstimateGb.toFixed(1) : "—";
    lines.push(
      `| ${i + 1} | ${rec.modelId} | ${rec.ihvProvider} | ${statusEmoji(rec.status)} ${rec.status} | ${formatDuration(rec.durationMs)} | ${rec.passCount} | ${vram} |`,
    );
  });

  lines.push("");

  // Per-job details
  lines.push("## Job Details");
  lines.push("");

  records.forEach((rec, i) => {
    lines.push(`### ${i + 1}. ${rec.modelId}`);
    lines.push("");
    lines.push(`- **Provider:** ${rec.ihvProvider}`);
    lines.push(`- **Memory Offload:** ${rec.memoryOffload}`);
    lines.push(`- **Status:** ${rec.status} (exit code: ${rec.exitCode ?? "n/a"})`);
    lines.push(`- **Duration:** ${formatDuration(rec.durationMs)}`);
    lines.push(`- **Timestamp:** ${rec.timestamp}`);
    lines.push(`- **Passes (${rec.passCount}):** ${rec.passNames.join(" → ")}`);

    if (rec.vramEstimateGb != null) {
      lines.push(`- **VRAM Estimate:** ${rec.vramEstimateGb.toFixed(2)} GB`);
    }

    if (includeLogSummary && rec.logSummary) {
      lines.push(`- **Logs:** ${rec.logSummary.totalLogs} total, ${rec.logSummary.errorCount} errors`);
      if (rec.logSummary.lastLog) {
        lines.push(`- **Last log:** \`${rec.logSummary.lastLog.slice(0, 200)}\``);
      }
    }

    if (includeRecipeJson && rec.recipeJson) {
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>Recipe JSON</summary>");
      lines.push("");
      lines.push("```json");
      try {
        lines.push(JSON.stringify(JSON.parse(rec.recipeJson), null, 2));
      } catch {
        lines.push(rec.recipeJson);
      }
      lines.push("```");
      lines.push("</details>");
    }

    lines.push("");
  });

  // Comparison section (if multiple records)
  if (records.length > 1) {
    lines.push("## Comparison");
    lines.push("");

    const completed = records.filter((r) => r.status === "completed");
    if (completed.length > 1) {
      const fastest = completed.reduce((a, b) => (a.durationMs < b.durationMs ? a : b));
      const smallest = completed
        .filter((r) => r.vramEstimateGb != null)
        .reduce(
          (a, b) => ((a.vramEstimateGb ?? Infinity) < (b.vramEstimateGb ?? Infinity) ? a : b),
          completed[0],
        );

      lines.push(`- **Fastest:** ${fastest.modelId} (${formatDuration(fastest.durationMs)})`);
      if (smallest.vramEstimateGb != null) {
        lines.push(`- **Lowest VRAM:** ${smallest.modelId} (${smallest.vramEstimateGb.toFixed(2)} GB)`);
      }

      const avgDuration = completed.reduce((sum, r) => sum + r.durationMs, 0) / completed.length;
      lines.push(`- **Average duration:** ${formatDuration(Math.round(avgDuration))}`);
    }

    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Olive Studio — local GUI for Microsoft Olive optimization*");
  lines.push("");

  return lines.join("\n");
}

/**
 * Trigger a browser download of the Markdown report.
 */
export function downloadMarkdownReport(records: JobHistoryRecord[], options: ReportOptions = {}): void {
  const markdown = generateMarkdownReport(records, options);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `olive-report-${new Date().toISOString().slice(0, 10)}.md`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

/**
 * Open a print-friendly window for PDF export via browser print dialog.
 */
export function printReportAsPdf(records: JobHistoryRecord[], options: ReportOptions = {}): void {
  const markdown = generateMarkdownReport(records, options);
  // Convert markdown to basic HTML for print
  const html = markdownToPrintHtml(markdown);
  const printWindow = window.open("", "_blank", "width=800,height=600");
  if (!printWindow) return;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  // Allow rendering before triggering print
  setTimeout(() => printWindow.print(), 250);
}

function markdownToPrintHtml(markdown: string): string {
  const escaped = markdown.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  // Process line-by-line to properly group tables and lists
  const lines = escaped.split("\n");
  const out: string[] = [];
  let inTable = false;
  let inList = false;

  for (const line of lines) {
    const isTableRow = /^\|(.+)\|$/.test(line.trim());
    const isSeparator = /^\|[\s\-:|]+\|$/.test(line.trim());
    const isListItem = /^- (.+)$/.test(line);

    // Close table if we're leaving table context
    if (inTable && !isTableRow) {
      out.push("</table>");
      inTable = false;
    }
    // Close list if we're leaving list context
    if (inList && !isListItem) {
      out.push("</ul>");
      inList = false;
    }

    if (isSeparator) {
      continue; // skip separator rows
    } else if (isTableRow) {
      if (!inTable) {
        out.push("<table>");
        inTable = true;
      }
      const cells = line
        .trim()
        .replace(/^\||\|$/g, "")
        .split("|")
        .map((c) => `<td>${inlineFmt(c.trim())}</td>`)
        .join("");
      out.push(`<tr>${cells}</tr>`);
    } else if (isListItem) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${inlineFmt(line.replace(/^- /, ""))}</li>`);
    } else if (/^### (.+)$/.test(line)) {
      out.push(`<h3>${inlineFmt(line.slice(4))}</h3>`);
    } else if (/^## (.+)$/.test(line)) {
      out.push(`<h2>${inlineFmt(line.slice(3))}</h2>`);
    } else if (/^# (.+)$/.test(line)) {
      out.push(`<h1>${inlineFmt(line.slice(2))}</h1>`);
    } else if (/^---$/.test(line)) {
      out.push("<hr/>");
    } else if (line.trim() === "") {
      out.push("<br/>");
    } else {
      out.push(`<p>${inlineFmt(line)}</p>`);
    }
  }
  if (inTable) out.push("</table>");
  if (inList) out.push("</ul>");

  const htmlBody = out.join("\n");

  return `<!DOCTYPE html>
<html>
<head>
<title>Olive Studio Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; color: #1a1a2e; font-size: 12px; }
  h1 { font-size: 1.5rem; border-bottom: 2px solid #3b82f6; padding-bottom: 0.5rem; }
  h2 { font-size: 1.2rem; margin-top: 1.5rem; color: #1e40af; }
  h3 { font-size: 1rem; margin-top: 1rem; }
  table { border-collapse: collapse; width: 100%; margin: 0.5rem 0; }
  tr, td { border: 1px solid #e2e8f0; padding: 4px 8px; text-align: left; }
  code { background: #f1f5f9; padding: 1px 4px; border-radius: 3px; font-size: 0.9em; }
  li { margin: 2px 0; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 1rem 0; }
  p { margin: 0.25rem 0; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>${htmlBody}</body>
</html>`;
}

/** Apply inline formatting (bold, italic, code) to a string. */
function inlineFmt(s: string): string {
  return s
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>");
}
