export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-enum": [
      1,
      "always",
      [
        "recipe-builder",
        "pipeline-validation",
        "recipe-pipeline",
        "quantization",
        "pruning",
        "peft",
        "conversion",
        "hardware-probe",
        "ai-assistant",
        "graph",
        "batch",
        "infra",
        "ui",
        "deps",
        "ci",
        "docs",
        "mcp",
        "types",
        "test",
        "chore",
        "fix",
        "perf",
        "refactor",
        "style",
        "build",
      ],
    ],
  },
};
