"""Tool: search_olive_documentation."""

import json
import time
from typing import Any

from . import KB_DIR


# Files that are generated by update_kb.py and should not be searched as KB.
_EXCLUDED_KB_FILES = {"update_report.json", "candidate_quirks.json"}

# Cache live docs for one hour so repeated searches do not hammer the network.
_LIVE_CACHE: dict[str, str] = {}
_LIVE_CACHE_TTL_SECONDS = 3600
_LAST_FETCH_TIME = 0.0


def _flatten(obj: Any, prefix: str = "") -> list[tuple[str, str]]:
    """Flatten a JSON object into (key-path, text) pairs for search."""
    results: list[tuple[str, str]] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            results.extend(_flatten(v, f"{prefix}.{k}"))
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            results.extend(_flatten(item, f"{prefix}[{i}]"))
    elif isinstance(obj, str):
        results.append((prefix, obj))
    return results


def _load_kb_text() -> list[tuple[str, str]]:
    all_text: list[tuple[str, str]] = []
    for file in KB_DIR.glob("*.json"):
        if file.name in _EXCLUDED_KB_FILES:
            continue
        try:
            with open(file, "r", encoding="utf-8") as f:
                data = json.load(f)
            for path, text in _flatten(data, prefix=file.stem):
                all_text.append((path, text))
        except Exception:
            continue
    return all_text


def _score_terms(text: str, terms: list[str]) -> int:
    text_lower = text.lower()
    return sum(1 for term in terms if term in text_lower)


def _rank_sources(sources: list[tuple[str, str]], terms: list[str], top_k: int) -> list[dict[str, Any]]:
    """Score `(path, text)` pairs against `terms` and return the top matches."""
    scored = []
    for path, text in sources:
        score = _score_terms(text, terms)
        if score == 0:
            continue
        scored.append({
            "source": path,
            "snippet": text[:300],
            "relevance": score,
        })
    scored.sort(key=lambda x: x["relevance"], reverse=True)
    return scored[:top_k]


def _search_local(terms: list[str], top_k: int) -> list[dict[str, Any]]:
    return _rank_sources(_load_kb_text(), terms, top_k)


def _fetch_live_docs() -> dict[str, str]:
    """Fetch (and cache) the live Olive docs landing page."""
    global _LIVE_CACHE, _LAST_FETCH_TIME  # noqa: PLW0603

    now = time.monotonic()
    if _LIVE_CACHE and (now - _LAST_FETCH_TIME) < _LIVE_CACHE_TTL_SECONDS:
        return _LIVE_CACHE

    try:
        # Lazy import: BeautifulSoup/requests are optional for local-KB-only search.
        from ..fetchers.official_docs_fetcher import fetch_official_docs

        result = fetch_official_docs(pages=["index"])
        if result.get("status") in ("ok", "partial"):
            pages = result.get("pages", {})
            fetched = {k: v for k, v in pages.items() if isinstance(v, str)}
            if fetched:
                _LIVE_CACHE = fetched
                _LAST_FETCH_TIME = now
    except Exception:  # noqa: BLE001
        pass  # Keep stale cache or return empty on failure.

    return _LIVE_CACHE


def _split_live_snippets(pages: dict[str, str]) -> list[tuple[str, str]]:
    """Break live page text into searchable snippets."""
    snippets: list[tuple[str, str]] = []
    for page, text in pages.items():
        for paragraph in text.split("\n\n"):
            paragraph = " ".join(paragraph.split()).strip()
            if paragraph:
                snippets.append((f"live:{page}", paragraph))
    return snippets


def _search_live(terms: list[str], top_k: int) -> list[dict[str, Any]]:
    try:
        pages = _fetch_live_docs()
        if not pages:
            return []
        return _rank_sources(_split_live_snippets(pages), terms, top_k)
    except Exception:  # noqa: BLE001
        return []


def search_olive_documentation(query: str, top_k: int = 5, live: bool = True) -> dict[str, Any]:
    """Full-text search across the local Olive knowledge base and live docs.

    Args:
        query: Search query, e.g. "calibrate static quantization".
        top_k: Maximum number of results (must be >= 0).
        live: Whether to include live results from https://microsoft.github.io/Olive/.

    Returns:
        Ranked results with snippet, source path, and relevance score.
    """
    if top_k < 0:
        raise ValueError(f"top_k must be >= 0, got {top_k}")

    terms = [t.lower() for t in query.split() if t]
    if not terms:
        return {"query": query, "count": 0, "results": [], "note": "Empty query."}

    # Over-fetch from each source so the merge has a reasonable pool.
    per_source = max(top_k * 2, 10)
    local_results = _search_local(terms, per_source)
    live_results = _search_live(terms, per_source) if live else []

    combined = local_results + live_results
    # For equal relevance, prefer live docs so fresh guidance surfaces first.
    combined.sort(
        key=lambda x: (-x["relevance"], 0 if x["source"].startswith("live:") else 1)
    )

    return {
        "query": query,
        "count": len(combined),
        "results": combined[:top_k],
        "note": (
            "Merged local knowledge base and live Olive docs results. "
            "Live docs are cached for one hour."
        ),
    }
