"""Tool: search_olive_documentation.

Semantic search over the local Olive knowledge base (and optional live docs),
with keyword fallback when nothing scores above the embedding threshold.
"""

from __future__ import annotations

import json
import threading
import time
from typing import Any

import numpy as np

from . import KB_DIR
from .embeddings import (
    DEFAULT_THRESHOLD,
    EMBEDDING_DIM,
    build_kb_index,
    semantic_search,
)


# Files that are generated by update_kb.py and should not be searched as KB.
_EXCLUDED_KB_FILES = {"update_report.json", "candidate_quirks.json"}

# Cache live docs for one hour so repeated searches do not hammer the network.
_LIVE_CACHE: dict[str, str] = {}
_LIVE_CACHE_TTL_SECONDS = 3600
_LAST_FETCH_TIME = 0.0
_LIVE_FETCH_LOCK = threading.Lock()
# Monotonic generation so out-of-order HTTP completions cannot overwrite a
# fresher cache entry started later.
_LIVE_FETCH_GENERATION = 0

# Live snippet embedding cache (tied to _LAST_FETCH_TIME).
_LIVE_SNIPPETS: list[tuple[str, str]] = []
_LIVE_EMBEDDINGS: np.ndarray | None = None
_LIVE_EMBED_CACHE_TIME = -1.0
_LIVE_INDEX_LOCK = threading.Lock()

# Local KB embedding index (invalidated when any KB JSON mtime changes).
_KB_TEXTS: list[tuple[str, str]] = []
_KB_EMBEDDINGS: np.ndarray | None = None
_KB_INDEX_MTIME = -1.0
_KB_INDEX_LOCK = threading.Lock()


def _flatten(obj: Any, prefix: str = "") -> list[tuple[str, str]]:
    """Flatten a JSON object into (key-path, text) pairs for search."""
    results: list[tuple[str, str]] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            results.extend(_flatten(v, f"{prefix}.{k}"))
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            results.extend(_flatten(item, f"{prefix}[{i}]"))
    elif isinstance(obj, str):
        results.append((prefix, obj))
    return results


def _load_kb_text() -> list[tuple[str, str]]:
    all_text: list[tuple[str, str]] = []
    for file in KB_DIR.glob("*.json"):
        if file.name in _EXCLUDED_KB_FILES:
            continue
        try:
            with open(file, "r", encoding="utf-8") as f:
                data = json.load(f)
            for path, text in _flatten(data, prefix=file.stem):
                all_text.append((path, text))
        except Exception:
            continue
    return all_text


def _kb_max_mtime() -> float:
    """Return the maximum mtime among searchable KB JSON files."""
    mtimes: list[float] = []
    for file in KB_DIR.glob("*.json"):
        if file.name in _EXCLUDED_KB_FILES:
            continue
        try:
            mtimes.append(file.stat().st_mtime)
        except OSError:
            continue
    return max(mtimes) if mtimes else 0.0


def get_or_build_kb_index() -> tuple[list[tuple[str, str]], np.ndarray]:
    """Public helper: lazy-build (and mtime-invalidate) the local KB embedding index.

    Used by docs search and passive context so both share one cache.
    Encode work runs outside the lock; the cache is only stamped when the KB
    mtime is unchanged from the value observed at load time (avoids publishing
    stale texts under a newer mtime after a mid-build hot-reload).
    """
    global _KB_TEXTS, _KB_EMBEDDINGS, _KB_INDEX_MTIME

    with _KB_INDEX_LOCK:
        current_mtime = _kb_max_mtime()
        if (
            _KB_EMBEDDINGS is not None
            and _KB_TEXTS is not None
            and _KB_INDEX_MTIME == current_mtime
        ):
            return _KB_TEXTS, _KB_EMBEDDINGS

    # Capture mtime at load time; only publish if it is still current later.
    build_mtime = _kb_max_mtime()
    texts = _load_kb_text()
    if not texts:
        embeddings: np.ndarray = np.zeros((0, EMBEDDING_DIM), dtype=np.float32)
    else:
        embeddings = build_kb_index([t for _, t in texts])

    with _KB_INDEX_LOCK:
        current_mtime = _kb_max_mtime()
        # Another thread may have already published a valid index for the current mtime.
        if (
            _KB_EMBEDDINGS is not None
            and _KB_TEXTS is not None
            and _KB_INDEX_MTIME == current_mtime
        ):
            return _KB_TEXTS, _KB_EMBEDDINGS

        if current_mtime != build_mtime:
            # KB changed mid-build: return this result without poisoning the cache
            # (stale content must not be stamped with the newer mtime).
            return texts, embeddings

        _KB_TEXTS = texts
        _KB_EMBEDDINGS = embeddings
        _KB_INDEX_MTIME = build_mtime
        return _KB_TEXTS, _KB_EMBEDDINGS


# Back-compat alias for internal callers / tests.
_get_kb_index = get_or_build_kb_index


def _score_terms(text: str, terms: list[str]) -> int:
    text_lower = text.lower()
    return sum(1 for term in terms if term in text_lower)


def _keyword_search(
    entries: list[tuple[str, str]],
    terms: list[str],
    top_k: int,
) -> list[dict[str, Any]]:
    """Keyword fallback: substring term matching against (source, text) pairs.

    Relevance is normalized to [0, 1] as hits / max(1, len(terms)) so it is
    commensurate with semantic cosine scores when sources are merged.
    """
    if not terms or top_k <= 0:
        return []
    denom = max(1, len(terms))
    scored: list[dict[str, Any]] = []
    for path, text in entries:
        hits = _score_terms(text, terms)
        if hits == 0:
            continue
        scored.append({
            "source": path,
            "snippet": text[:300],
            "relevance": hits / denom,
        })
    scored.sort(key=lambda x: x["relevance"], reverse=True)
    return scored[:top_k]


def _search_local(query: str, top_k: int) -> list[dict[str, Any]]:
    """Semantic search over the local KB, with keyword fallback."""
    terms = [t.lower() for t in query.split() if t]

    try:
        kb_texts, embeddings = get_or_build_kb_index()
        results = semantic_search(
            query,
            kb_texts,
            embeddings,
            top_k,
            threshold=DEFAULT_THRESHOLD,
        )
        if results:
            return results
    except Exception:  # noqa: BLE001
        pass

    return _keyword_search(_load_kb_text(), terms, top_k)


def _fetch_live_docs() -> dict[str, str]:
    """Fetch (and cache) the live Olive docs landing page.

    Concurrent fetches take a generation token; only the latest generation may
    publish, so a slow older response cannot overwrite a fresher one.
    """
    global _LIVE_CACHE, _LAST_FETCH_TIME, _LIVE_FETCH_GENERATION  # noqa: PLW0603

    with _LIVE_FETCH_LOCK:
        now = time.monotonic()
        if _LIVE_CACHE and (now - _LAST_FETCH_TIME) < _LIVE_CACHE_TTL_SECONDS:
            return dict(_LIVE_CACHE)
        _LIVE_FETCH_GENERATION += 1
        my_generation = _LIVE_FETCH_GENERATION

    try:
        # Lazy import: BeautifulSoup/requests are optional for local-KB-only search.
        from ..fetchers.official_docs_fetcher import fetch_official_docs

        result = fetch_official_docs(pages=["index"])
        if result.get("status") in ("ok", "partial"):
            pages = result.get("pages", {})
            fetched = {k: v for k, v in pages.items() if isinstance(v, str)}
            if fetched:
                with _LIVE_FETCH_LOCK:
                    # Ignore stale completions if a newer fetch was started.
                    if my_generation == _LIVE_FETCH_GENERATION:
                        _LIVE_CACHE = fetched
                        _LAST_FETCH_TIME = time.monotonic()
    except Exception:  # noqa: BLE001
        pass  # Keep stale cache or return empty on failure.

    with _LIVE_FETCH_LOCK:
        return dict(_LIVE_CACHE)


def _split_live_snippets(pages: dict[str, str]) -> list[tuple[str, str]]:
    """Break live page text into searchable snippets."""
    snippets: list[tuple[str, str]] = []
    for page, text in pages.items():
        for paragraph in text.split("\n\n"):
            paragraph = " ".join(paragraph.split()).strip()
            if paragraph:
                snippets.append((f"live:{page}", paragraph))
    return snippets


def _get_live_index() -> tuple[list[tuple[str, str]], np.ndarray]:
    """Return live snippets and their embeddings, rebuilding on cache refresh."""
    global _LIVE_SNIPPETS, _LIVE_EMBEDDINGS, _LIVE_EMBED_CACHE_TIME

    pages = _fetch_live_docs()
    with _LIVE_FETCH_LOCK:
        fetch_time = _LAST_FETCH_TIME

    with _LIVE_INDEX_LOCK:
        if (
            _LIVE_EMBEDDINGS is not None
            and _LIVE_SNIPPETS
            and _LIVE_EMBED_CACHE_TIME == fetch_time
        ):
            return _LIVE_SNIPPETS, _LIVE_EMBEDDINGS

    snippets = _split_live_snippets(pages) if pages else []
    if not snippets:
        embeddings: np.ndarray = np.zeros((0, EMBEDDING_DIM), dtype=np.float32)
    else:
        embeddings = build_kb_index([t for _, t in snippets])

    with _LIVE_INDEX_LOCK:
        if (
            _LIVE_EMBEDDINGS is not None
            and _LIVE_SNIPPETS
            and _LIVE_EMBED_CACHE_TIME == fetch_time
        ):
            return _LIVE_SNIPPETS, _LIVE_EMBEDDINGS

        _LIVE_SNIPPETS = snippets
        _LIVE_EMBEDDINGS = embeddings
        _LIVE_EMBED_CACHE_TIME = fetch_time
        return _LIVE_SNIPPETS, _LIVE_EMBEDDINGS


def _search_live(query: str, top_k: int) -> list[dict[str, Any]]:
    """Semantic search over live docs snippets, with keyword fallback."""
    terms = [t.lower() for t in query.split() if t]
    try:
        snippets, embeddings = _get_live_index()
        if not snippets:
            return []
        results = semantic_search(
            query,
            snippets,
            embeddings,
            top_k,
            threshold=DEFAULT_THRESHOLD,
        )
        if results:
            return results
        return _keyword_search(snippets, terms, top_k)
    except Exception:  # noqa: BLE001
        try:
            pages = _fetch_live_docs()
            if not pages:
                return []
            return _keyword_search(_split_live_snippets(pages), terms, top_k)
        except Exception:  # noqa: BLE001
            return []


def search_olive_documentation(query: str, top_k: int = 5, live: bool = True) -> dict[str, Any]:
    """Full-text search across the local Olive knowledge base and live docs.

    Args:
        query: Search query, e.g. "calibrate static quantization".
        top_k: Maximum number of results (must be >= 0).
        live: Whether to include live results from https://microsoft.github.io/Olive/.

    Returns:
        Ranked results with snippet, source path, and relevance score.
        ``relevance`` is in roughly [0, 1] for both semantic and keyword modes.
    """
    if top_k < 0:
        raise ValueError(f"top_k must be >= 0, got {top_k}")

    terms = [t.lower() for t in query.split() if t]
    if not terms:
        return {"query": query, "count": 0, "results": [], "note": "Empty query."}

    per_source = max(top_k * 2, 10)
    local_results = _search_local(query, per_source)
    live_results = _search_live(query, per_source) if live else []

    combined = local_results + live_results
    combined.sort(
        key=lambda x: (-x["relevance"], 0 if x["source"].startswith("live:") else 1)
    )

    results = combined[:top_k]
    if (
        live_results
        and top_k > 0
        and results
        and not any(r["source"].startswith("live:") for r in results)
    ):
        best_live = max(live_results, key=lambda x: x["relevance"])
        if top_k == 1:
            results = [best_live]
        else:
            results = results[: top_k - 1] + [best_live]
            results.sort(
                key=lambda x: (-x["relevance"], 0 if x["source"].startswith("live:") else 1)
            )

    return {
        "query": query,
        "count": len(combined),
        "results": results,
        "note": (
            "Merged local knowledge base and live Olive docs results. "
            "Live docs are cached for one hour."
        ),
    }
